export const ADMIN_ERRORS = {
  username_taken: 'That username is already in use.',
  invalid_username: '3–32 characters: letters, numbers, dot, dash, underscore.',
  password_too_short: 'Password must be at least 8 characters.',
  last_admin: 'There must always be at least one admin.',
  cannot_demote_self: 'You cannot remove your own admin rights.',
  cannot_delete_self: 'You cannot delete your own account.',
  store_exists: 'That store already exists.',
  invalid_store: 'Enter a store name.',
  unknown_store: 'Choose a store from the list.',
  brand_exists: 'That brand already exists.',
  invalid_brand: 'Enter a brand name.',
  unknown_brand: 'Choose a brand from the list.',
  category_exists: 'That category already exists.',
  invalid_category: 'Enter a category name.',
  unknown_category: 'Choose a category from the list.',
  unsupported_version: 'That file is not a supported Stockaroo backup.',
  no_admin_in_backup: 'That backup contains no admin user.',
  invalid_payload: 'That file is not a valid backup.',
  invalid_barcode: 'Enter a valid barcode.',
  barcode_in_use: 'That barcode is already used by another item.',
  last_barcode: 'An item needs at least one barcode.',
  invalid_merge: 'Choose a different item to merge into.',
  mqtt_missing_config: 'Enter a broker URL and topic before enabling MQTT.',
  invalid_delta: 'Enter a non-zero scan amount between -1000 and 1000.'
};
